In [73]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns

In [74]:
df=pd.read_csv("/Users/rakeshsharma/Documents/Interview Questions for Data Engineer/Self Machine Learning Folder/Placement.CSV") 

In [75]:
df.head()

cgpa  package
0  6.89     3.26
1  5.12     1.98
2  7.82     3.25
3  7.42     3.67
4  6.94     3.57

In [76]:
df

cgpa  package
0    6.89     3.26
1    5.12     1.98
2    7.82     3.25
3    7.42     3.67
4    6.94     3.57
..    ...      ...
195  6.93     2.46
196  5.89     2.57
197  7.21     3.24
198  7.63     3.96
199  6.22     2.33

[200 rows x 2 columns]

In [77]:
sns.scatterplot(df,x='cgpa',y='package')
plt.title('Linear Regression Plot')
plt.xlabel('CGPA')
plt.ylabel('Package')
plt.show()


In [78]:
x=df.iloc[:,0:1]
y=df.iloc[:,-1]

In [79]:
y

0      3.26
1      1.98
2      3.25
3      3.67
4      3.57
       ... 
195    2.46
196    2.57
197    3.24
198    3.96
199    2.33
Name: package, Length: 200, dtype: float64

In [80]:
x

cgpa
0    6.89
1    5.12
2    7.82
3    7.42
4    6.94
..    ...
195  6.93
196  5.89
197  7.21
198  7.63
199  6.22

[200 rows x 1 columns]

In [81]:
from sklearn.model_selection import train_test_split
x_train,x_test, y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [82]:
x_train.shape ,x_test.shape ,y_train.shape ,y_test.shape

((160, 1), (40, 1), (160,), (40,))

In [83]:
from sklearn.linear_model import LinearRegression

In [84]:
lr=LinearRegression()

In [85]:
lr.fit(x_train,y_train)

LinearRegression()

In [86]:
x_test

cgpa
112  8.58
29   7.15
182  5.88
199  6.22
193  4.57
85   4.79
10   5.32
54   6.86
115  8.35
35   6.87
12   8.94
92   7.90
13   6.93
126  5.91
174  7.32
2    7.82
44   5.09
3    7.42
113  6.94
14   7.73
23   6.19
25   7.28
6    6.73
134  7.20
165  8.21
173  6.75
45   7.87
65   7.60
48   8.63
122  5.12
178  8.15
64   7.36
9    8.31
57   6.60
78   6.59
71   7.47
128  7.93
176  6.29
131  6.37
53   6.47

In [87]:
y_test

112    4.10
29     3.49
182    2.08
199    2.33
193    1.94
85     1.48
10     1.86
54     3.09
115    4.21
35     2.87
12     3.65
92     4.00
13     2.89
126    2.60
174    2.99
2      3.25
44     1.86
3      3.67
113    2.37
14     3.42
23     2.48
25     3.65
6      2.60
134    2.83
165    4.08
173    2.56
45     3.58
65     3.81
48     4.09
122    2.01
178    3.63
64     2.92
9      3.51
57     1.94
78     2.21
71     3.34
128    3.34
176    3.23
131    2.01
53     2.61
Name: package, dtype: float64

In [88]:
import warnings
warnings.filterwarnings("ignore")

In [89]:
lr.predict(x_test.iloc[0].values.reshape(1,1))



array([3.89111601])

In [90]:
sns.scatterplot(df,x='cgpa',y='package')
plt.plot(x_train,lr.predict(x_train),color='red')
plt.title('Linear Regression Plot')
plt.xlabel('CGPA')
plt.ylabel('Package')
plt.show()

In [91]:
m=lr.coef_
m

array([0.55795197])

In [92]:
b=lr.intercept_
b

-0.8961119222429144

In [70]:
#y = mx + b
m* 8.58 + b



NameError: name 'm' is not defined

In [93]:
m* 9.1 + b



array([4.18125104])

In [95]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Assuming LR is your linear regression model
y_pred = lr.predict(x_test)  # Predicted values
y_true = y_test  # True values from the test set

# Calculate evaluation metrics
mae = mean_absolute_error(y_true, y_pred)
mse = mean_squared_error(y_true, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_true, y_pred)

print("Mean Absolute Error:", mae)
print("Mean Squared Error:", mse)
print("Root Mean Squared Error:", rmse)
print("R-squared:", r2)


Mean Absolute Error: 0.2884710931878175
Mean Squared Error: 0.12129235313495527
Root Mean Squared Error: 0.34827051717731616
R-squared: 0.780730147510384
